In [94]:
import pandas as pd

In [95]:
df = pd.read_csv('100_Unique_QA_Dataset.csv')

In [96]:
df

                                             question        answer
0                      What is the capital of France?         Paris
1                     What is the capital of Germany?        Berlin
2                  Who wrote 'To Kill a Mockingbird'?    Harper-Lee
3     What is the largest planet in our solar system?       Jupiter
4      What is the boiling point of water in Celsius?           100
..                                                ...           ...
85                  Who directed the movie 'Titanic'?  JamesCameron
86  Which superhero is also known as the Dark Knight?        Batman
87                     What is the capital of Brazil?      Brasilia
88        Which fruit is known as the king of fruits?         Mango
89       Which country is known for the Eiffel Tower?        France

[90 rows x 2 columns]

In [97]:
# tokenize
def tokenize(text):
  text = text.lower()
  text = text.replace(',', '')
  text = text.replace('.', '')
  text = text.replace('?', '')
  text = text.replace("'","")
  return text.split()

In [98]:

tokenize("hello, how. 'are' you?")

['hello', 'how', 'are', 'you']

In [99]:
# voclabary
vocab = {'UKN':0}

In [100]:
# vocablary function where vocab is built
def build_vocab(row):

  tokenizes_question = tokenize(row['question'])
  tokenizes_answer = tokenize(row['answer'])

  merged_tokens = tokenizes_question + tokenizes_answer

  for token in merged_tokens:
    if token not in vocab:
      vocab[token] = len(vocab)

In [101]:
df.apply(build_vocab,axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [102]:

# unique words in our dataset
vocab

{'UKN': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 '1984': 67,
 'george-orwell': 68,
 'currency': 69,
 'united': 70,
 'kingdom': 71,
 'pound': 72,
 'india': 73,
 'delhi': 74,
 'discovered': 75,
 'gravity': 76,
 'newton': 77,
 'how': 78,
 'many': 79,
 'continents': 80,
 'are': 81,
 'there': 82,
 'on': 83,
 'earth': 84,
 '7': 85,
 'gas': 86,
 'do': 87,
 'plants': 88,
 'use': 89,
 'photosynthesis': 90,
 'co2': 91,
 'smallest': 92,
 'prime': 93,
 'number': 94,
 '2': 95,
 'invented': 96,
 'telephone': 97,
 'alexander-graham-bell': 98,
 'australia': 99,
 'canberra': 100,
 'ocean': 101,
 'pacific-ocean': 102,
 'speed': 103,
 'light': 104,
 'vacuum': 105,
 '299792458m/s': 106,
 'language': 107,
 'spoken': 108,
 'brazil': 109,
 'portuguese': 110,
 'penicillin': 111,
 'alexander-fleming': 112,
 'canada': 113,
 'ottawa': 114,
 'mammal': 115,
 'whale': 116,
 'element': 117,
 'has': 118,
 'atomic': 119,
 '1': 120,
 'hydrogen': 121,
 'tallest': 122,
 'mountain': 123,
 'everest': 124,
 'city': 125,
 'big': 126,
 'apple': 127,
 'newyork': 128,
 'planets': 129,
 'starry': 130,
 'night': 131,
 'vangogh': 132,
 'formula': 133,
 'h2o': 134,
 'italy': 135,
 'rome': 136,
 'country': 137,
 'famous': 138,
 'sushi': 139,
 'was': 140,
 'first': 141,
 'person': 142,
 'step': 143,
 'moon': 144,
 'armstrong': 145,
 'main': 146,
 'ingredient': 147,
 'guacamole': 148,
 'avocado': 149,
 'sides': 150,
 'does': 151,
 'hexagon': 152,
 'have': 153,
 '6': 154,
 'china': 155,
 'yuan': 156,
 'pride': 157,
 'and': 158,
 'prejudice': 159,
 'jane-austen': 160,
 'iron': 161,
 'fe': 162,
 'hardest': 163,
 'natural': 164,
 'substance': 165,
 'diamond': 166,
 'continent': 167,
 'by': 168,
 'area': 169,
 'asia': 170,
 'president': 171,
 'states': 172,
 'george-washington': 173,
 'bird': 174,
 'its': 175,
 'ability': 176,
 'mimic': 177,
 'sounds': 178,
 'parrot': 179,
 'longest-running': 180,
 'animated': 181,
 'tv': 182,
 'show': 183,
 'simpsons': 184,
 'vaticancity': 185,
 'most': 186,
 'moons': 187,
 'saturn': 188,
 'romeo': 189,
 'juliet': 190,
 'shakespeare': 191,
 'earths': 192,
 'atmosphere': 193,
 'nitrogen': 194,
 'bones': 195,
 'adult': 196,
 'human': 197,
 'body': 198,
 '206': 199,
 'metal': 200,
 'liquid': 201,
 'at': 202,
 'room': 203,
 'temperature': 204,
 'mercury': 205,
 'russia': 206,
 'moscow': 207,
 'electricity': 208,
 'benjamin-franklin': 209,
 'second-largest': 210,
 'land': 211,
 'color': 212,
 'ripe': 213,
 'banana': 214,
 'yellow': 215,
 'month': 216,
 '28': 217,
 'days': 218,
 'common': 219,
 'february': 220,
 'study': 221,
 'living': 222,
 'organisms': 223,
 'called': 224,
 'biology': 225,
 'home': 226,
 'great': 227,
 'wall': 228,
 'bees': 229,
 'collect': 230,
 'from': 231,
 'flowers': 232,
 'nectar': 233,
 'opposite': 234,
 'day': 235,
 'south': 236,
 'korea': 237,
 'seoul': 238,
 'bulb': 239,
 'edison': 240,
 'humans': 241,
 'breathe': 242,
 'survival': 243,
 'oxygen': 244,
 '144': 245,
 '12': 246,
 'pyramids': 247,
 'giza': 248,
 'egypt': 249,
 'sea': 250,
 'creature': 251,
 'eight': 252,
 'arms': 253,
 'octopus': 254,
 'holiday': 255,
 'celebrated': 256,
 'december': 257,
 '25': 258,
 'christmas': 259,
 'yen': 260,
 'legs': 261,
 'spider': 262,
 'sport': 263,
 'uses': 264,
 'net': 265,
 'ball': 266,
 'hoop': 267,
 'basketball': 268,
 'kangaroos': 269,
 'female': 270,
 'minister': 271,
 'uk': 272,
 'margaretthatcher': 273,
 'fastest': 274,
 'animal': 275,
 'cheetah': 276,
 'periodic': 277,
 'table': 278,
 'spain': 279,
 'madrid': 280,
 'closest': 281,
 'sun': 282,
 'father': 283,
 'computers': 284,
 'charlesbabbage': 285,
 'mexico': 286,
 'mexicocity': 287,
 'colors': 288,
 'rainbow': 289,
 'musical': 290,
 'instrument': 291,
 'black': 292,
 'white': 293,
 'keys': 294,
 'piano': 295,
 'americas': 296,
 '1492': 297,
 'christophercolumbus': 298,
 'disney': 299,
 'character': 300,
 'long': 301,
 'nose': 302,
 'grows': 303,
 'it': 304,
 'when': 305,
 'lying': 306,
 'pinocchio': 307,
 'directed': 308,
 'movie': 309,
 'titanic': 310,
 'jamescameron': 311,
 'superhero': 312,
 'also': 313,
 'dark': 314,
 'knight': 315,
 'batman': 316,
 'brasilia': 317,
 'fruit': 318,
 'king': 319,
 'fruits': 320,
 'mango': 321,
 'eiffel': 322,
 'tower': 323}

In [103]:
# conver words to numirical index
def text_to_indexes(text,vocab):

  indexed_text = []

  for token in tokenize(text):

    if token in vocab:
      indexed_text.append(vocab[token])

    else:
      indexed_text.append(vocab['UKN'])

  return indexed_text

In [104]:

text_to_indexes("what is onepiece",vocab)
# here we are getting indexies when text is given w.r.s to vocablary build above

[1, 2, 0]

In [105]:
import torch

from torch.utils.data import Dataset, DataLoader

In [106]:
from numpy._core import numeric
class QADataset(Dataset):

  def __init__(self,df,vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self, index):

    numerical_question = text_to_indexes(self.df.iloc[index]['question'],self.vocab)

    numerical_answer = text_to_indexes(self.df.iloc[index]['answer'],self.vocab)

    return torch.tensor(numerical_question), torch.tensor(numerical_answer)

In [107]:
dataset = QADataset(df, vocab)

In [108]:
dataset[0]

(tensor([1, 2, 3, 4, 5, 6]), tensor([7]))

In [109]:
dataloader = DataLoader(dataset, batch_size = 1,shuffle=True)

In [110]:
for questions, answers in dataloader:
  print(questions,answers)

tensor([[42, 18,  2, 62, 63,  3, 64, 18]]) tensor([[65]])
tensor([[ 42, 318,   2,  62,  63,   3, 319,   5, 320]]) tensor([[321]])
tensor([[ 42, 255,   2, 256,  83, 257, 258]]) tensor([[259]])
tensor([[  1,  87, 229, 230, 231, 232]]) tensor([[233]])
tensor([[ 42,   2,   3, 210, 137, 168, 211, 169]]) tensor([[113]])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([[41]])
tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]]) tensor([[179]])
tensor([[10, 29,  3, 30, 31]]) tensor([[32]])
tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]]) tensor([[199]])
tensor([[ 78,  79, 261, 151,  14, 262, 153]]) tensor([[36]])
tensor([[ 42,  86,  87, 241, 242,  19,  39, 243]]) tensor([[244]])
tensor([[10, 75, 76]]) tensor([[77]])
tensor([[ 42, 137, 118,   3, 247,   5, 248]]) tensor([[249]])
tensor([[  1,   2,   3,   4,   5, 135]]) tensor([[136]])
tensor([[  1,   2,   3,   4,   5, 109]]) tensor([[317]])
tensor([[ 78,  79, 150, 151,  14, 152, 153]]) tensor([[154]])
tensor([[ 42, 167,   2,   3,  17, 168, 169]]) tensor([[170]])
tensor([[  1,   2,   3, 212,   5,  14, 213, 214]]) tensor([[215]])
tensor([[ 10,  11, 157, 158, 159]]) tensor([[160]])
tensor([[ 42, 299, 300, 118,  14, 301, 302, 158, 303, 304, 305, 306]]) tensor([[307]])
tensor([[ 42, 200,   2,  14, 201, 202, 203, 204]]) tensor([[205]])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([[124]])
tensor([[ 42, 250, 251, 118, 252, 253]]) tensor([[254]])
tensor([[ 42, 137,   2,  62,  39,   3, 322, 323]]) tensor([[6]])
tensor([[42, 86, 87, 88, 89, 39, 90]]) tensor([[91]])
tensor([[ 42, 137,   2, 138,  39, 175, 269]]) tensor([[99]])
tensor([[ 10,  75, 111]]) tensor([[112]])
tensor([[  1,   2,   3,  37,  38,  39, 161]]) tensor([[162]])
tensor([[  1,   2,   3,   4,   5, 236, 237]]) tensor([[238]])
tensor([[ 10, 140,   3, 141, 270,  93, 271,   5,   3, 272]]) tensor([[273]])
tensor([[ 10,  96,   3, 104, 239]]) tensor([[240]])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([[9]])
tensor([[  1,   2,   3,  69,   5, 155]]) tensor([[156]])
tensor([[  1,   2,   3,  33,  34,   5, 245]]) tensor([[246]])
tensor([[ 42, 312,   2, 313,  62,  63,   3, 314, 315]]) tensor([[316]])
tensor([[  1,   2,   3,   4,   5, 206]]) tensor([[207]])
tensor([[  1,   2,   3, 234,   5, 235]]) tensor([[131]])
tensor([[ 10,  75,   3, 296,  19, 297]]) tensor([[298]])
tensor([[ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]]) tensor([[145]])
tensor([[ 42,   2,   3, 274, 211, 275]]) tensor([[276]])
tensor([[  1,   2,   3, 221,   5, 222, 223, 224]]) tensor([[225]])
tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]]) tensor([[36]])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([[54]])
tensor([[  1,   2,   3,   4,   5, 286]]) tensor([[287]])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([[28]])
tensor([[ 1,  2,  3,  4,  5, 99]]) tensor([[100]])
tensor([[ 42,  18, 118,   3, 186, 187]]) tensor([[188]])
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([[116]])
tensor([[ 42, 137,   2, 226,  12,   3, 227, 228]]) tensor([[155]])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([[7]])
tensor([[ 42, 137,   2, 138,  39, 139]]) tensor([[53]])
tensor([[10, 96,  3, 97]]) tensor([[98]])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]) tensor([[185]])
tensor([[ 42, 101,   2,   3,  17]]) tensor([[102]])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([[49]])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([[106]])
tensor([[ 42, 216, 118, 217, 218,  19,  14, 219,  43]]) tensor([[220]])
tensor([[ 42, 263, 264,  14, 265, 266, 158, 267]]) tensor([[268]])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([[16]])
tensor([[  1,   2,   3, 146,  86,  19, 192, 193]]) tensor([[194]])
tensor([[ 1,  2,  3, 92, 93, 94]]) tensor([[95]])
tensor([[ 10,   2,  62,  63,   3, 283,   5, 284]]) tensor([[285]])
tensor([[ 78,  79, 288,  81,  19,  14, 289]]) tensor([[85]])
tensor([[ 10, 140,   3, 141, 171,   5,   3,  70, 172]]) tensor([[173]])
tensor([[ 10,  11, 189, 158, 190]]) tensor([[191]])
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([[74]])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]) tensor([[72]])
tensor([[10,  2,  3, 66,  5, 67]]) tensor([[68]])
tensor([[ 10,  75, 208]]) tensor([[209]])
tensor([[ 10,  29, 130, 131]]) tensor([[132]])
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([[134]])
tensor([[  1,   2,   3, 141, 117,  83,   3, 277, 278]]) tensor([[121]])
tensor([[ 1,  2,  3, 33, 34,  5, 35]]) tensor([[36]])
tensor([[  1,   2,   3, 180, 181, 182, 183]]) tensor([[184]])
tensor([[78, 79, 80, 81, 82, 83, 84]]) tensor([[85]])
tensor([[ 42, 117, 118,   3, 119,  94, 120]]) tensor([[121]])
tensor([[  1,   2,   3,   4,   5, 279]]) tensor([[280]])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([[23]])
tensor([[ 10, 308,   3, 309, 310]]) tensor([[311]])
tensor([[10, 55,  3, 56,  5, 57]]) tensor([[58]])
tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]]) tensor([[52]])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]) tensor([[128]])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([[61]])
tensor([[  1,   2,   3, 163, 164, 165,  83,  84]]) tensor([[166]])
tensor([[ 1,  2,  3, 69,  5, 53]]) tensor([[260]])
tensor([[ 42,  18,   2,   3, 281,  12,   3, 282]]) tensor([[205]])
tensor([[ 42, 290, 291, 118, 292, 158, 293, 294]]) tensor([[295]])
tensor([[  1,   2,   3,   4,   5, 113]]) tensor([[114]])
tensor([[  1,   2,   3, 146, 147,  19, 148]]) tensor([[149]])
tensor([[ 42, 107,   2, 108,  19, 109]]) tensor([[110]])

In [111]:
import torch.nn as nn

In [131]:
class SimpleRnn(nn.Module):
  def __init__(self,voclab_Size):
    super().__init__()
    self.embedding = nn.Embedding(voclab_Size,embedding_dim=50)
    self.rnn = nn.RNN(50,64,batch_first = True)
    self.fc = nn.Linear(64,voclab_Size)

  def forward(self, input_tensor):
    embedded_questions = self.embedding(input_tensor)
    hidden, final = self.rnn(embedded_questions)
    output = self.fc(final.squeeze(0))

    return output

In [113]:
dataset[0]

(tensor([1, 2, 3, 4, 5, 6]), tensor([7]))

In [114]:
x =  nn.Embedding(324,embedding_dim=50)

In [115]:
a = x(dataset[0][0])
# here the embeddings is working fine, where there are 6 vectors of 50 dimentions each

In [116]:
a

tensor([[-1.0474e+00, -8.6015e-01, -1.4854e+00,  6.9924e-01, -1.0026e+00,
          1.8254e+00, -1.3294e-01,  3.4652e-01, -2.1206e+00, -1.4389e-01,
          9.3882e-01,  1.2054e+00, -1.1148e+00, -1.6716e+00, -1.2995e+00,
          1.0160e+00,  8.2815e-01,  7.2202e-01,  4.3125e-01,  1.5541e-01,
          1.1019e+00,  1.8470e-01, -2.9995e-01,  3.8346e-01, -3.0086e-01,
         -1.8549e-01,  1.1351e+00, -5.4901e-01, -5.6971e-01,  5.0376e-01,
          5.6203e-01,  2.5812e-01, -3.8660e-01, -6.6896e-01,  2.2210e-01,
         -9.2555e-01,  2.0176e+00,  7.2872e-02,  5.2016e-01, -2.9497e-01,
          1.6104e+00,  3.3195e-01,  1.3636e-01, -3.0833e-01,  1.3186e+00,
         -1.0556e+00,  1.4591e+00,  1.1216e+00, -2.4926e+00,  3.3130e-01],
        [ 1.0011e+00, -1.7723e+00, -1.1899e+00,  1.2692e+00,  1.4472e-01,
          7.2261e-01,  1.4988e+00,  1.0362e+00, -1.2375e+00, -1.0955e+00,
         -1.3922e+00, -1.7680e+00,  6.3831e-01, -1.1681e+00, -1.8573e+00,
         -2.5576e-01,  8.8187e-01, -8.5232e-01,  2.0514e-01, -1.6230e+00,
         -4.0344e-01,  1.1412e+00, -2.0335e+00,  1.5025e+00,  8.5403e-01,
         -5.4602e-01,  2.2332e-01,  7.7284e-02, -5.8621e-01,  1.2811e+00,
          3.3181e-02, -6.8811e-03, -1.5084e+00, -6.2184e-01,  2.6931e-02,
         -2.9314e-01,  3.7089e-01, -6.3861e-01, -8.7482e-01, -6.7186e-02,
         -3.8847e-01, -5.5869e-01,  2.0674e+00,  4.6645e-01, -1.1406e+00,
          1.2883e+00, -5.2079e-01,  4.7753e-01, -1.0641e+00, -4.0207e-01],
        [ 2.4343e-01, -7.6643e-01,  1.7461e+00,  2.5291e-01,  1.3582e+00,
          1.3487e+00,  1.4220e+00, -6.5814e-01,  1.5014e+00, -5.5156e-01,
          1.2002e+00,  1.0459e+00,  8.1201e-01, -1.4617e-01,  1.6379e+00,
          7.1012e-01,  6.9797e-01, -1.6686e-01,  1.5685e+00,  2.3733e-01,
          1.6733e+00,  7.1653e-02,  1.0560e+00,  8.1652e-01, -2.3427e-01,
          1.2321e+00,  8.1802e-01,  2.3553e+00, -1.5234e+00,  1.5198e-01,
         -4.6524e-01,  7.6641e-01,  1.8121e-01, -9.6726e-01, -9.7479e-01,
         -1.8807e-01, -9.6012e-02,  1.0074e+00,  1.2138e+00,  1.9838e+00,
          1.9564e-01,  1.1487e+00, -3.7042e-03, -1.9289e-01, -1.0249e+00,
          1.6486e+00,  4.4271e-01, -6.2306e-01, -1.3945e-01, -5.1398e-01],
        [ 1.2458e+00, -9.6846e-01, -7.8912e-01,  1.1536e+00,  2.7786e+00,
          4.1802e-01, -3.2531e-01,  9.6613e-01, -1.7087e+00,  7.4444e-01,
         -1.1971e+00, -1.4885e-01, -9.1334e-01,  5.0832e-01, -3.0614e-01,
          1.7645e-01,  1.0519e+00, -2.6561e-01, -1.4330e+00, -1.2036e+00,
          3.6816e-01,  8.9752e-01, -1.3600e+00,  1.5447e+00,  4.8872e-01,
          1.0835e+00,  1.4255e+00,  3.8278e-01,  1.3625e-01,  2.1875e+00,
         -1.3239e+00,  4.7208e-01, -9.5073e-03,  2.2535e+00, -3.7222e-01,
         -1.4999e+00,  2.4247e+00,  5.7184e-01,  1.5250e+00,  1.3658e+00,
          4.6157e-01, -8.7982e-02, -1.2621e+00,  5.3464e-01,  2.0884e+00,
         -5.8696e-01, -8.2796e-01,  1.7105e+00, -1.0729e+00,  4.4563e-01],
        [-9.7337e-01, -5.3509e-01, -8.6210e-01, -4.4188e-01,  7.3395e-02,
         -1.4066e+00, -9.4631e-01,  3.5060e-01,  1.0598e+00,  4.6705e-01,
         -2.4246e-01, -8.9386e-01,  1.4065e+00, -5.5311e-01,  1.7919e+00,
         -8.8719e-01,  3.1844e-03,  2.6527e+00,  3.7232e-01, -3.3502e-01,
         -6.6063e-01, -4.8476e-02, -4.4990e-01, -1.1396e+00, -5.7636e-01,
          1.0483e+00,  4.7653e-01, -8.4854e-01, -1.3595e+00,  1.1705e+00,
          8.6443e-01, -8.7729e-01,  3.3398e+00, -2.5909e-01, -8.1120e-01,
         -2.0280e-01, -8.4431e-01, -1.0316e+00,  5.8725e-01,  2.5567e-01,
         -6.9247e-01,  9.3846e-01, -2.1835e+00, -2.1654e-01, -1.3650e-01,
         -7.2170e-03, -2.5083e-01,  1.6050e+00, -5.0789e-01,  6.6971e-01],
        [-6.3047e-01, -1.8189e+00, -9.2759e-01, -1.5401e+00,  2.8929e-01,
          2.3265e+00, -4.3724e-01,  1.4046e+00, -1.5869e+00, -2.7503e-01,
         -2.6763e+00,  3.3805e-01, -1.0596e+00, -1.2034e+00,  1.5059e+00,
         -1.9050e+00, -9.0844e-01,  3.1983e+00,  1.3974e+00,  6.9273e-01,
         -6.6479e-01,  9.7054e-01, -4.0715e-01, -3.1089e-01, -6.5882e-01,
         -1.1038e+00, -4.0125e-01, -3.4192e-01,  6.2046e-01,  4.0851e-01,
         -1.0144e-01,  6.8865e-01, -4.6386e-01, -6.0473e-01, -1.0390e-01,
         -2.8554e-03, -8.0499e-01, -1.1865e+00,  1.2408e+00, -9.8291e-01,
         -1.0435e+00,  1.2017e+00, -1.3793e+00,  1.1155e+00,  1.0327e-01,
          2.0837e-01,  5.9302e-01, -4.1066e-01,  1.6171e-01,  4.5680e-01]],
       grad_fn=<EmbeddingBackward0>)

In [117]:
x(dataset[0][0]).shape
# shape of our vector where there are 6 vectors of 50 dimentionals

torch.Size([6, 50])

In [118]:
y = nn.RNN(50,64)

In [119]:
y(a)

(tensor([[ 0.0267,  0.3677, -0.3188,  0.3641,  0.1059,  0.0343, -0.3426, -0.5761,
          -0.3074,  0.1160, -0.4312,  0.1129, -0.5735,  0.1420,  0.4463, -0.0086,
           0.0700, -0.3893,  0.3444,  0.0794,  0.0194,  0.2539,  0.0876, -0.0338,
          -0.1734,  0.5910,  0.1322,  0.3013, -0.5193, -0.1256,  0.2972,  0.4003,
           0.5470, -0.4756,  0.0631, -0.8436, -0.0671,  0.4881, -0.6129, -0.1772,
           0.3601, -0.2836, -0.0686, -0.2726,  0.2000, -0.2823, -0.5231, -0.4138,
           0.0771, -0.1257,  0.3184, -0.0741,  0.4675, -0.5926, -0.1125, -0.8481,
          -0.1240, -0.2984, -0.2211,  0.1337, -0.3716,  0.2883, -0.0432, -0.4107],
         [-0.4499,  0.2455,  0.2097, -0.3248,  0.5704, -0.0814, -0.3741,  0.0258,
           0.1596,  0.0715, -0.0597, -0.4457, -0.7355,  0.4356,  0.4014, -0.1296,
           0.4243, -0.0161,  0.7919,  0.3466, -0.1881,  0.2513, -0.7328,  0.6154,
          -0.5923, -0.3384, -0.7352,  0.6049,  0.1434,  0.5288,  0.3356,  0.3169,
          -0.6491,  0.6894,  0.5214, -0.5336,  0.3707,  0.5398, -0.8855,  0.7455,
           0.1347,  0.4748,  0.2450, -0.2731,  0.7603, -0.1696,  0.5817,  0.3964,
           0.5776,  0.5627,  0.2733,  0.2493,  0.3648,  0.6439, -0.4692, -0.5624,
          -0.1101,  0.2650,  0.0275, -0.8035,  0.6457, -0.7786, -0.1262, -0.1296],
         [-0.6927,  0.4544, -0.3538, -0.6193, -0.0305, -0.2701, -0.3913, -0.2055,
          -0.2842, -0.0077, -0.0690,  0.6554,  0.6895,  0.4066, -0.2234, -0.7858,
           0.6975,  0.5100,  0.6915,  0.3002, -0.4837, -0.6484, -0.7353,  0.3793,
          -0.5497, -0.1199, -0.7713, -0.1508, -0.0798, -0.1550,  0.2490,  0.5713,
          -0.0825,  0.2721, -0.6584,  0.4209, -0.5263,  0.4805,  0.3485,  0.1512,
           0.6991, -0.0944,  0.6087, -0.1080, -0.5832, -0.6102,  0.2037,  0.1395,
           0.1016, -0.3124, -0.6692,  0.1569,  0.8660, -0.0170,  0.8193,  0.6458,
          -0.2012,  0.6624, -0.4684,  0.3451, -0.1983,  0.6934,  0.0112, -0.4429],
         [ 0.4668, -0.6551,  0.3368, -0.5370,  0.2867, -0.0408, -0.2752,  0.0824,
           0.3986, -0.7007, -0.4833, -0.4068,  0.1907,  0.6538,  0.0620, -0.4033,
          -0.8943, -0.7096,  0.2809, -0.5301, -0.1244,  0.2967, -0.4720,  0.5175,
          -0.4065,  0.0867,  0.3094, -0.2171,  0.8946, -0.6881,  0.4966,  0.8406,
          -0.7217, -0.0859,  0.3992, -0.9191, -0.7781,  0.2471, -0.2109, -0.1435,
           0.2126,  0.6293, -0.0835, -0.5901,  0.4320, -0.3438,  0.7697,  0.0844,
          -0.2007, -0.4187, -0.3661,  0.2170,  0.4090,  0.6754, -0.0356, -0.8560,
          -0.8139,  0.6656, -0.4934, -0.1516,  0.2111, -0.3252, -0.5058,  0.3610],
         [-0.5156,  0.5914,  0.1713, -0.2229,  0.5273, -0.8657,  0.1678, -0.8654,
          -0.2121,  0.9353, -0.1421,  0.0489, -0.3032,  0.2269, -0.5642, -0.2399,
           0.0942,  0.0981, -0.7430,  0.4595, -0.7411,  0.1460, -0.1061, -0.1381,
          -0.1085,  0.1015,  0.2115, -0.4471, -0.5436,  0.1065,  0.3389, -0.3510,
          -0.6181,  0.4796,  0.1377,  0.4980, -0.2882, -0.5658, -0.0102,  0.4394,
           0.2587, -0.4341, -0.0108, -0.3644,  0.6088, -0.7017, -0.6105,  0.2397,
          -0.6384,  0.6400,  0.4326, -0.0703, -0.6467,  0.2162, -0.4374,  0.1373,
          -0.0705,  0.7466, -0.0928,  0.4004, -0.5208, -0.1779,  0.2492,  0.2612],
         [-0.6760,  0.3084, -0.3611, -0.2351,  0.3352, -0.3977, -0.1990,  0.5035,
           0.1940,  0.6942, -0.4697, -0.5571,  0.0634, -0.0522,  0.1898, -0.5809,
           0.6679,  0.6621, -0.5115,  0.0326,  0.6698,  0.5870, -0.1689,  0.7366,
          -0.1390,  0.4896, -0.0056, -0.4749, -0.4171, -0.3118, -0.6984,  0.8850,
          -0.5899, -0.8298, -0.6279,  0.6870,  0.7230,  0.7584, -0.7550, -0.4314,
          -0.1251,  0.1134, -0.1426, -0.7309,  0.9017, -0.4669, -0.6118,  0.4865,
           0.0558,  0.3594,  0.0291, -0.4875,  0.3978,  0.0400, -0.2156, -0.7233,
           0.9286,  0.3340, -0.2470,  0.3639,  0.1803,  0.3777, -0.6288,  0.0662]],
        grad_fn=<SqueezeBackward1>),
 tensor([[-0.6760,  0.3084, -0.3611, -0.2351,  0.3352, -0.3977, -0.1990,  0.5035,
           0.1940,  0.6942, -0.4697, -0.5571,  0.0634, -0.0522,  0.1898, -0.5809,
           0.6679,  0.6621, -0.5115,  0.0326,  0.6698,  0.5870, -0.1689,  0.7366,
          -0.1390,  0.4896, -0.0056, -0.4749, -0.4171, -0.3118, -0.6984,  0.8850,
          -0.5899, -0.8298, -0.6279,  0.6870,  0.7230,  0.7584, -0.7550, -0.4314,
          -0.1251,  0.1134, -0.1426, -0.7309,  0.9017, -0.4669, -0.6118,  0.4865,
           0.0558,  0.3594,  0.0291, -0.4875,  0.3978,  0.0400, -0.2156, -0.7233,
           0.9286,  0.3340, -0.2470,  0.3639,  0.1803,  0.3777, -0.6288,  0.0662]],
        grad_fn=<SqueezeBackward1>))

In [120]:
y(a) # we got two tensors here

(tensor([[ 0.0267,  0.3677, -0.3188,  0.3641,  0.1059,  0.0343, -0.3426, -0.5761,
          -0.3074,  0.1160, -0.4312,  0.1129, -0.5735,  0.1420,  0.4463, -0.0086,
           0.0700, -0.3893,  0.3444,  0.0794,  0.0194,  0.2539,  0.0876, -0.0338,
          -0.1734,  0.5910,  0.1322,  0.3013, -0.5193, -0.1256,  0.2972,  0.4003,
           0.5470, -0.4756,  0.0631, -0.8436, -0.0671,  0.4881, -0.6129, -0.1772,
           0.3601, -0.2836, -0.0686, -0.2726,  0.2000, -0.2823, -0.5231, -0.4138,
           0.0771, -0.1257,  0.3184, -0.0741,  0.4675, -0.5926, -0.1125, -0.8481,
          -0.1240, -0.2984, -0.2211,  0.1337, -0.3716,  0.2883, -0.0432, -0.4107],
         [-0.4499,  0.2455,  0.2097, -0.3248,  0.5704, -0.0814, -0.3741,  0.0258,
           0.1596,  0.0715, -0.0597, -0.4457, -0.7355,  0.4356,  0.4014, -0.1296,
           0.4243, -0.0161,  0.7919,  0.3466, -0.1881,  0.2513, -0.7328,  0.6154,
          -0.5923, -0.3384, -0.7352,  0.6049,  0.1434,  0.5288,  0.3356,  0.3169,
          -0.6491,  0.6894,  0.5214, -0.5336,  0.3707,  0.5398, -0.8855,  0.7455,
           0.1347,  0.4748,  0.2450, -0.2731,  0.7603, -0.1696,  0.5817,  0.3964,
           0.5776,  0.5627,  0.2733,  0.2493,  0.3648,  0.6439, -0.4692, -0.5624,
          -0.1101,  0.2650,  0.0275, -0.8035,  0.6457, -0.7786, -0.1262, -0.1296],
         [-0.6927,  0.4544, -0.3538, -0.6193, -0.0305, -0.2701, -0.3913, -0.2055,
          -0.2842, -0.0077, -0.0690,  0.6554,  0.6895,  0.4066, -0.2234, -0.7858,
           0.6975,  0.5100,  0.6915,  0.3002, -0.4837, -0.6484, -0.7353,  0.3793,
          -0.5497, -0.1199, -0.7713, -0.1508, -0.0798, -0.1550,  0.2490,  0.5713,
          -0.0825,  0.2721, -0.6584,  0.4209, -0.5263,  0.4805,  0.3485,  0.1512,
           0.6991, -0.0944,  0.6087, -0.1080, -0.5832, -0.6102,  0.2037,  0.1395,
           0.1016, -0.3124, -0.6692,  0.1569,  0.8660, -0.0170,  0.8193,  0.6458,
          -0.2012,  0.6624, -0.4684,  0.3451, -0.1983,  0.6934,  0.0112, -0.4429],
         [ 0.4668, -0.6551,  0.3368, -0.5370,  0.2867, -0.0408, -0.2752,  0.0824,
           0.3986, -0.7007, -0.4833, -0.4068,  0.1907,  0.6538,  0.0620, -0.4033,
          -0.8943, -0.7096,  0.2809, -0.5301, -0.1244,  0.2967, -0.4720,  0.5175,
          -0.4065,  0.0867,  0.3094, -0.2171,  0.8946, -0.6881,  0.4966,  0.8406,
          -0.7217, -0.0859,  0.3992, -0.9191, -0.7781,  0.2471, -0.2109, -0.1435,
           0.2126,  0.6293, -0.0835, -0.5901,  0.4320, -0.3438,  0.7697,  0.0844,
          -0.2007, -0.4187, -0.3661,  0.2170,  0.4090,  0.6754, -0.0356, -0.8560,
          -0.8139,  0.6656, -0.4934, -0.1516,  0.2111, -0.3252, -0.5058,  0.3610],
         [-0.5156,  0.5914,  0.1713, -0.2229,  0.5273, -0.8657,  0.1678, -0.8654,
          -0.2121,  0.9353, -0.1421,  0.0489, -0.3032,  0.2269, -0.5642, -0.2399,
           0.0942,  0.0981, -0.7430,  0.4595, -0.7411,  0.1460, -0.1061, -0.1381,
          -0.1085,  0.1015,  0.2115, -0.4471, -0.5436,  0.1065,  0.3389, -0.3510,
          -0.6181,  0.4796,  0.1377,  0.4980, -0.2882, -0.5658, -0.0102,  0.4394,
           0.2587, -0.4341, -0.0108, -0.3644,  0.6088, -0.7017, -0.6105,  0.2397,
          -0.6384,  0.6400,  0.4326, -0.0703, -0.6467,  0.2162, -0.4374,  0.1373,
          -0.0705,  0.7466, -0.0928,  0.4004, -0.5208, -0.1779,  0.2492,  0.2612],
         [-0.6760,  0.3084, -0.3611, -0.2351,  0.3352, -0.3977, -0.1990,  0.5035,
           0.1940,  0.6942, -0.4697, -0.5571,  0.0634, -0.0522,  0.1898, -0.5809,
           0.6679,  0.6621, -0.5115,  0.0326,  0.6698,  0.5870, -0.1689,  0.7366,
          -0.1390,  0.4896, -0.0056, -0.4749, -0.4171, -0.3118, -0.6984,  0.8850,
          -0.5899, -0.8298, -0.6279,  0.6870,  0.7230,  0.7584, -0.7550, -0.4314,
          -0.1251,  0.1134, -0.1426, -0.7309,  0.9017, -0.4669, -0.6118,  0.4865,
           0.0558,  0.3594,  0.0291, -0.4875,  0.3978,  0.0400, -0.2156, -0.7233,
           0.9286,  0.3340, -0.2470,  0.3639,  0.1803,  0.3777, -0.6288,  0.0662]],
        grad_fn=<SqueezeBackward1>),
 tensor([[-0.6760,  0.3084, -0.3611, -0.2351,  0.3352, -0.3977, -0.1990,  0.5035,
           0.1940,  0.6942, -0.4697, -0.5571,  0.0634, -0.0522,  0.1898, -0.5809,
           0.6679,  0.6621, -0.5115,  0.0326,  0.6698,  0.5870, -0.1689,  0.7366,
          -0.1390,  0.4896, -0.0056, -0.4749, -0.4171, -0.3118, -0.6984,  0.8850,
          -0.5899, -0.8298, -0.6279,  0.6870,  0.7230,  0.7584, -0.7550, -0.4314,
          -0.1251,  0.1134, -0.1426, -0.7309,  0.9017, -0.4669, -0.6118,  0.4865,
           0.0558,  0.3594,  0.0291, -0.4875,  0.3978,  0.0400, -0.2156, -0.7233,
           0.9286,  0.3340, -0.2470,  0.3639,  0.1803,  0.3777, -0.6288,  0.0662]],
        grad_fn=<SqueezeBackward1>))

In [121]:
y(a)[0].shape # hidden state

torch.Size([6, 64])

In [122]:
b = y(a)[1] # final state

In [123]:
z = nn.Linear(64,324)

In [124]:
z(b)

tensor([[-0.5438,  0.3801,  0.2492,  0.0571, -0.3371, -0.0391,  0.1060, -0.2393,
         -0.3935,  0.1648, -0.0670,  0.1826, -0.3943,  0.3538,  0.2407,  0.2420,
         -0.4088,  0.4704, -0.5160, -0.4404,  0.1385,  0.3200,  0.1979, -0.6650,
         -0.1650,  0.5849,  0.6746, -0.4023, -0.2149,  0.8844, -0.1256, -0.4666,
         -0.0542, -0.3217,  0.0106, -0.1562, -0.1979,  0.3570, -0.2450, -0.1131,
          0.4357, -0.0503,  0.1315, -0.1787, -0.4391,  0.0118,  0.5101,  0.3588,
          0.2334,  0.1319, -0.2023,  0.1668, -0.3529,  0.2832,  0.2084,  0.2424,
         -0.0987,  0.4355, -0.1982,  0.0630, -0.0732,  0.3883,  0.0062,  0.1346,
          0.3994,  0.4786, -0.0183,  0.5269, -0.3535, -0.1605, -0.1925, -0.2859,
         -0.5506, -0.2004, -0.2557, -0.5377,  0.1865, -0.1751,  0.0396,  0.2997,
          0.0228,  0.1594,  0.0817,  0.2346, -0.2104, -0.1103,  0.2213, -0.8196,
         -0.3992, -0.0211, -0.2081, -0.1330, -0.4751,  0.2462,  0.1140,  0.1863,
          0.1921, -0.0021, -0.1318,  0.2286, -0.1416, -0.4110,  0.0917, -0.4007,
          0.4486,  0.6728,  0.0098, -0.1805,  0.0786,  0.1052, -0.6299, -0.3680,
         -0.6033, -0.4522,  0.4238, -0.0691,  0.0365,  0.1610,  0.1707,  0.1267,
         -0.2599, -0.4836,  0.1020,  0.3904, -0.1923,  0.4133,  0.0305, -0.2999,
          0.0799, -0.3577,  0.3827,  0.0817, -0.2007,  0.4811,  0.3319,  0.0530,
         -0.0960,  0.1145, -0.1296, -0.0470, -0.2841, -0.0824,  0.1286,  0.0362,
          0.1390,  0.1009,  0.2746, -0.1304,  0.0653,  0.1447, -0.4109, -0.3989,
          0.1976,  0.1212, -0.3829, -0.1193, -0.1713, -0.0184,  0.1666, -0.4814,
          0.1704, -0.0800, -0.2083,  0.2484, -0.2092, -0.3904, -0.1502,  0.0327,
          0.0599,  0.4000, -0.1959,  0.0715,  0.0929, -0.0503,  0.3335,  0.1133,
         -0.1369,  0.2322,  0.3818, -0.3275, -0.0210, -0.9177,  0.2917, -0.1824,
         -0.3617,  0.2421,  0.2023,  0.0787, -0.3096,  0.0336,  0.0047,  0.7141,
          0.3284, -0.3687, -0.0068,  0.3010, -0.4364,  0.0073,  0.2271,  0.2463,
         -0.1373,  0.0992,  0.0781,  0.8026,  0.1701, -0.3810, -0.1242, -0.1384,
          0.0409,  0.4589,  0.3234,  0.0321,  0.1759,  0.5574,  0.1924, -0.5018,
         -0.4687,  0.4998,  0.0580,  0.0570,  0.3492, -0.5496, -0.1169,  0.0868,
         -0.0087,  0.1227,  0.0502,  0.4183,  0.3145, -0.3025,  0.2518, -0.0260,
         -0.0935,  0.1553, -0.2533,  0.7856,  0.4613,  0.2681, -0.2153, -0.3349,
         -0.0914,  0.4157, -0.0447,  0.2764,  0.3795,  0.0875,  0.1609,  0.2867,
          0.2640, -0.5183, -0.3650, -0.3322, -0.2171,  0.2775, -0.1969,  0.0360,
          0.2044, -0.2828, -0.0469, -0.0317, -0.2109,  0.1729, -0.1767, -0.2079,
         -0.2084, -0.4501,  0.1135, -0.0734,  0.2438,  0.3214, -0.3410, -0.1825,
         -0.0479,  0.0304, -0.2513, -0.1144,  0.1654, -0.3049, -0.3820, -0.2487,
         -0.0758, -0.1352, -0.5978,  0.4494,  0.1090, -0.4788, -0.2785,  0.1918,
          0.0638, -0.3657, -0.0991, -0.5227, -0.0926, -0.4212,  0.2008, -0.0494,
          0.1016, -0.2401,  0.5146, -0.0905,  0.6533,  0.3437, -0.0292, -0.6113,
          0.1958, -0.3546, -0.0372,  0.1512,  0.4169, -0.3204, -0.0381,  0.1399,
         -0.1814,  0.1798, -0.0724,  0.4370,  0.1368,  0.5053,  0.4811, -0.3617,
         -0.0631,  0.2245, -0.0393,  0.6117]], grad_fn=<AddmmBackward0>)

In [125]:
z(b).shape # for each word in vocalabry we are getting probablity

torch.Size([1, 324])

In [126]:
learning_rate = 0.001
epochs = 20

In [132]:
model = SimpleRnn(len(vocab))

In [133]:
criterion =  nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

In [135]:
# training

for echos in range(epochs):
  total_loss = 0

  for questions, answers in dataloader:
    optimizer.zero_grad()

    # forward pass
    output = model(questions)

    # loss
    loss = criterion(output, answers.squeeze(1))

    # gredident claculate
    loss.backward()

    # update gradidents
    optimizer.step()

    total_loss = total_loss + loss.item()

  # The original code had a typo `epoch` instead of `echos`.
  print(f"epoch {echos + 1},Loss {total_loss:.4f}")

epoch 1,Loss 525.2455
epoch 2,Loss 460.1332
epoch 3,Loss 383.0451
epoch 4,Loss 319.4938
epoch 5,Loss 267.1983
epoch 6,Loss 219.1135
epoch 7,Loss 174.7487
epoch 8,Loss 135.9678
epoch 9,Loss 103.9639
epoch 10,Loss 79.0536
epoch 11,Loss 60.6482
epoch 12,Loss 47.0214
epoch 13,Loss 37.2547
epoch 14,Loss 29.9018
epoch 15,Loss 24.6631
epoch 16,Loss 20.4687
epoch 17,Loss 17.3311
epoch 18,Loss 14.7279
epoch 19,Loss 12.7605
epoch 20,Loss 10.9383

In [148]:
def predict(model, question, treshold=0.5):
  # convert question to numbers
  numerical_question = text_to_indexes(question, vocab)

  #convert num to rensors
  question_tensor = torch.tensor(numerical_question).unsqueeze(0)
  #send to model
  output = model(question_tensor)

  #convert logits to probs
  probs =torch.nn.functional.softmax(output, dim=1)

  #find index of max prob
  value, index = torch.max(probs, dim=1)

  # check treshold
  if value < treshold:
    print('i dont know..!')

  else:
    print(list(vocab.keys())[index])

In [149]:
predict(model, "what is onepiece")

i dont know..!

In [150]:
predict(model, "what is the capital of france")

paris

In [151]:
predict(model, "what is the largest planet of our solar system")

jupiter

In [152]:
predict(model, "say my name")

i dont know..!